markdown: kramdown
exclude:
  - LICENSE

layouts: ./_noita
baseurl: https://math240-LU.github.io

noita:
  name: Math 240 - Probability (Fall 2015)
  description: Jekyll theme built with Foundation
  author:
    name: Adam Loy
    url: http://aloy.github.io
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Schedule
        url: /
      - name: Info
        url: /info/
      - name: Syllabus
        url: /syllabus/
      - name: Resources
        url: /resources/
      - name: Moodle
        url: https://moodle.lawrence.edu/
        absolute: true
      - name: Links
        url: /links/